version: '3.6'

services:
  chatgpt:
    build: .
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./components:/app/components
      - ./styles:/app/styles
      - ./utils:/app/utils
      - ./types:/app/types
      - ./services:/app/services
    ports:
      - 8095:3000
    command: "npm run start"
